
# Docker compose with postgres
services:
  database:
    image: postgres:15.6
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - db_data:/var/lib/postgresql/data:Z
  jupyter:
    image: jupyter/datascience-notebook:latest
    environment:
      JUPYTER_ENABLE_LAB: "yes"
      NOTEBOOK_ALLOW_ORIGIN: '*'
      JUPYTER_TOKEN: ''
      JUPYTER_PASSWORD: ''
    command: ["jupyter", "notebook", "--NotebookApp.token=''", "--NotebookApp.password=''", "--allow-root", "--port=8080", "--no-browser", "--ip=0.0.0.0"]
    ports:
      - "8080:8080"
    volumes:
      - ./notebooks:/home/jovyan/work
    links:
      - database

volumes:
  db_data:
